services:
  web:
    container_name: d-odoo
    image: odoo:18
    depends_on:
      - db
    ports:
      - 8069:8069
    volumes:
      - ./odoo/addons:/mnt/extra-addons
      - ./odoo/filestore:/var/lib/odoo/filestore
      - ./odoo/sessions:/var/lib/odoo/sessions
      - ./odoo/config:/etc/odoo
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    command: --dev=all

  # Database management in a single PHP file.
  # Comprobaremos si se crean las bases de datos
  adminer:
    container_name: d-adminer
    image: adminer:standalone
    restart: always
    ports:
      - 8080:8080

  db:
    container_name: d-postgres
    image: postgres:17.6
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_DB=postgres
    volumes:
      - ./odoo/dataPostgreSQL:/var/lib/postgresql/data
